### ISSUE TITLE
Error when trying to run the node.js site

### ISSUE THREAD

**Issue by mlanderos** [floyd-may/hwaas#1]
Hi Floyd, I followed along your SaltStack video on Plural Sight to create the hwaas site. Unfortunately, when I get to the part of starting the nodejs app I get the following response. I tried to manipulate the .js file some because when I put it though a JS lint it complained about a few things, but I still couldn't get it to work.

[root@Web01 hwaas-site]# node .

/home/hwaas/hwaas-site/app/index.js:6
var server = http.createServer((req, res) => {
                                                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by floyd-may** [comment]
I suspect you may have an outdated version of Node.js installed.

**Comment by mlanderos** [comment]
node -v returns 0.10.48 and npm -v returns 1.3.6
I am running CentOS and had Salt  Master install nodejs package like your video. 
Once thing that is slightly odd is you call "nodejs ." but nodejs doesn't operate for me. Only node. Ill continue to research.
